workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - build
  - deploy

variables:
  TOMCAT_HOME: "C:\Esfita\Software\apache-tomcat-10.1.34"
  WAR_NAME: "service-registry-scm.war"

build-war:
  stage: build
  tags:
    - tomcat
  script:
    - gradlew.bat clean build -x test
  artifacts:
    paths:
      - build/libs/*.war

deploy-to-tomcat:
  stage: deploy
  tags:
    - tomcat
  needs:
    - build-war
  script:
    - echo Stopping Tomcat
    - "%TOMCAT_HOME%\\bin\\shutdown.bat"
    - timeout /t 5
    - echo Deploying WAR
    - copy /Y build\\libs\\%WAR_NAME% %TOMCAT_HOME%\\webapps\\%WAR_NAME%
    - echo Starting Tomcat
    - "%TOMCAT_HOME%\\bin\\startup.bat"
