spring.application.name=service-registry-scm

#local
#server.port=8761

#live
server.port=9070

server.servlet.context-path=/service-registry-scm

eureka.instance.hostname=localhost

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
